name: Convert YAML to ARM Template

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  convert:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Action to checkout the repository

    - name: Install PowerShell module for YAML
      run: |
        pwsh -c "Install-Module -Name powershell-yaml -Force -Scope CurrentUser -AllowClobber"

    - name: Convert YAML to ARM Template
      shell: pwsh  # Use PowerShell shell
      run: |
        Import-Module .\ConvertHuntingQueryFromYamlToArm.ps1

        $newDirectory = New-Item -ItemType Directory -Path ".\Hunting"
        Write-Host 'new Directory: $newDirectory'
        foreach($parserYaml in $(Get-Item ***\*.yaml))
        {
             $outputFilePath = "$($newDirectory.FullName)\$($parserYaml.BaseName).json"
             ConvertHuntingQueryFromYamlToArm $parserYaml.FullName $outputFilePath
        }
