name: Convert YAML to ARM Template

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  convert:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Action to checkout the repository
    
    - name: Set up PowerShell
      uses: microsoft/powershell@v1  # Use PowerShell action provided by Microsoft

    - name: Install PowerShell module for YAML
      run: |
        Install-Module -Name powershell-yaml -Force -Scope CurrentUser -AllowClobber

    - name: Create output directory
      run: |
        New-Item -ItemType Directory -Path ./Hunting -Force

    - name: Convert YAML to ARM Template
      shell: pwsh  # Use PowerShell shell
      run: |
        foreach ($yamlFile in -Path 'KQL' -Filter '*.yaml') {
          $outputFilePath = "./Hunting/$($yamlFile.BaseName).json"
          .\ConvertHuntingQueryFromYamlToArm.ps1 -inputFilePath $yamlFile.FullName -outputFilePath $outputFilePath
        }
