on:
  push:
    branches: [main]
    paths:
      - "KQL/*.yaml"
  workflow_dispatch:

permissions:
  contents: write

name: Build ARM Analytic Rules

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ARM Analytic Rules
    steps:
      - uses: actions/checkout@v3
        with:
          path: Sigma2KQL-v2  # Specify the directory where you want to checkout your repository
      - name: Convert YAML rule to ARM
        run: |
          Install-Module SentinelARConverter -AcceptLicense -Force
          Get-ChildItem -Path 'Sigma2KQL-v2/KQL' -Filter '*.yaml' | ForEach-Object {
              Write-Output "Processing file: $($_.Name)"
              Write-Output "Full path: $($_.FullName)"  # Debugging output
              $yamlFilePath = $_.FullName.Replace('.yaml', '.json')
              Write-Output "Target JSON file path: $yamlFilePath"  # Debugging output
              if (-not (Test-Path $yamlFilePath) -or (Get-Item $yamlFilePath).LastWriteTime -lt $_.LastWriteTime) {
                  Write-Host "Converting $($_.FullName) to $yamlFilePath"
                  Convert-SentinelARYamlToArm -Filename $_.FullName -UseOriginalFilename
              }
          }
        shell: pwsh
      - name: Commit and push changes
        run: |
          git config --global user.name 'Khaled6120'
          git config --global user.email 'khalednaes3@gmail.com'
          git add KQL
          git commit -am "SentinelARConverter"
          git push
