name: Convert YAML to ARM Template

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  convert:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Action to checkout the repository

    - name: Install PowerShell module for YAML
      run: |
        pwsh -c "Install-Module -Name powershell-yaml -Force -Scope CurrentUser -AllowClobber"

    - name: Convert YAML to ARM Template
      shell: pwsh  # Use PowerShell shell
      run: |
        Import-Module .\ConvertHuntingQueryFromYamlToArm.ps1
        if (-not (Test-Path -Path 'Hunting')) {
              New-Item -ItemType Directory -Path 'Hunting'
        }

        $newDirectory = New-Item -ItemType Directory -Path ".\Hunting"
        Write-Host "New Directory: $($newDirectory.FullName)"
        Get-ChildItem -Path './KQL' -Filter '*.yaml' | ForEach-Object {
            $yamlFilePath = $_.FullName
            $outputFilePath = Join-Path -Path $newDirectory.FullName -ChildPath "$($_.BaseName).json"
            
            # Call your conversion function with appropriate parameters
            ConvertHuntingQueryFromYamlToArm -inputFilePath $yamlFilePath -outputFilePath $outputFilePath
            
            Write-Host "Converted $($_.Name) to $($outputFilePath)"
        }
