name: Convert YAML to ARM Template

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  convert:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Action to checkout the repository

    - name: Install PowerShell module for YAML
      run: |
        pwsh -c "Install-Module -Name powershell-yaml -Force -Scope CurrentUser -AllowClobber"

    - name: Convert YAML to ARM Template
      shell: pwsh  # Use PowerShell shell
      run: |
        Import-Module .\ConvertHuntingQueryFromYamlToArm.ps1
        
        # Check if 'Hunting' directory exists; create if not
        if (-not (Test-Path -Path './Hunting')) {
          New-Item -ItemType Directory -Path './Hunting'
          Write-Host "Created directory: ./Hunting"
        } else {
          Write-Host "Directory './Hunting' already exists."
        }
        
        Write-Host "Current Directory: $(Get-Location)"

        # Check if 'Hunting' directory exists; create if not
        $newDirectory = New-Item -ItemType Directory -Path "./Hunting" -Force
        Write-Host "New Directory: $($newDirectory.FullName)"

        # Iterate through each YAML file in the 'KQL' directory
        Get-ChildItem -Path './KQL' -Filter '*.yaml' | ForEach-Object {
            $yamlFilePath = $_.FullName
            Write-Host 'Yamlfilepath:$($_.FullName)'
            $outputFilePath = Join-Path -Path './Hunting' -ChildPath "$($_.BaseName).json"
            
            # Call your conversion function with appropriate parameters
            ConvertHuntingQueryFromYamlToArm -inputFilePath KQL/$($_.Name) -outputFilePath $outputFilePath
            
            Write-Host "Converted $($_.Name) to $($outputFilePath)"
        }
        - name: Commit and push changes
        run: |
          git config --global user.name 'Khaled6120'
          git config --global user.email 'khalednaes3@gmail.com'
          git add Hunting
          git commit -am "huntingRules"
          git push
