on:
  push:
    branches: [main]
    paths:
      - "KQL/*.yaml"
  workflow_dispatch:

permissions:
  contents: write

name: Build ARM Hunt Rules

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ARM Analytic Rules
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Install PowerShell-yaml module
        run: |
          pwsh -Command "Install-Module PowerShell-yaml -Force -AllowClobber -Scope CurrentUser"
          shell: pwsh 
      - name: Convert yaml rules to JSON/arm
        run: |
          Import-Module ConvertHuntingQueryFromYamlToArm.ps1
          
          $newDirectory = New-Item -ItemType Directory -Path "HuntingRules"
          foreach($parserYaml in $(Get-Item KQL\*.yaml))
          {
               $outputFilePath = "$($newDirectory.FullName)\$($parserYaml.BaseName).json"
               ConvertHuntingQueryFromYamlToArm $parserYaml.FullName $outputFilePath
          }
        shell: pwsh
